import { createServer } from "node:http";
import { afterEach, describe, expect, it } from "vitest";
import type { FactsSnapshot } from "@harnessme/core";
import { authorHarnessWithAi } from "../packages/analyzers/src/harness-author.js";
import type { AnalysisResult } from "../packages/analyzers/src/types.js";

const servers: Array<ReturnType<typeof createServer>> = [];

afterEach(async () => {
  await Promise.all(servers.splice(0).map((server) => new Promise<void>((resolve, reject) => {
    server.close((error) => error ? reject(error) : resolve());
  })));
});

function harnessMarkdown(includeArchitecture: boolean): string {
  return `# Repository instructions

## Stack

A repository fixture used to verify harness generation.

## Before editing

Before editing, inspect the owning code and nearby tests.

## Reference map

No scoped reference is needed for this empty fixture.

${includeArchitecture ? "## Architecture\n\nNo stable module boundaries were detected.\n\n" : ""}## Coding conventions

Follow repository-local configuration.

## Operating rules

- Keep changes scoped to the owning module.
- Run repository checks before considering work complete.

## Known documentation conflicts

No documentation conflicts were detected.

## Core boundaries

No concrete core boundary was detected in this empty fixture.

## Change workflows

- Edit behavior through the owning module and update its tests.
- Trace affected callers and verify public contracts before changing them.

## Validation

No validation command was detected.

## Documentation maintenance

Update repository documentation when public behavior changes.

## Critical-path safety gate

Before editing a listed path, stop and ask the developer for explicit confirmation. Never self-approve or bypass the gate.

{{HARNESSME_CRITICAL_PATHS}}

## Verified material changes

{{HARNESSME_VERIFIED_CHANGES}}

## Project directives

{{HARNESSME_DIRECTIVES}}

## Keeping this harness current

{{HARNESSME_PENDING}}`;
}

function operationalHarnessMarkdown(): string {
  return `<!-- Generated by HarnessME. Do not edit outside the PENDING section. -->
# Repository instructions

## Stack

TypeScript runtime and tooling.

## Before editing

Before editing, inspect \`src/core.ts\`, its callers, nearby tests, and \`docs/CORE.md\`.

## Reference map

- [Core change guide](.harnessme/references/core.md): Read before changing the core service.

## Architecture

The \`src/\` module contains the application core.

## Coding conventions

Preserve the existing service boundary. Evidence: \`src/core.ts:1\`.

## Operating rules

- Keep changes inside the owning module unless a public contract requires coordinated edits. Evidence: \`src/core.ts:1\`.
- Preserve the service boundary and update its consumers together.
- Run the validated checks before considering work complete.

## Known documentation conflicts

No documentation conflicts were detected.

## Core boundaries

- \`src/core.ts\` owns the shared service contract. Ask before changing its public behavior.

## Change workflows

- Edit the service through \`src/core.ts\` and update its consumers together.
- Update nearby tests and run the validated checks after behavior changes.

## Validation

Run \`npm test\` after changing behavior.

## Documentation maintenance

Update \`docs/CORE.md\` when the shared service contract changes.

## Critical-path safety gate

Before editing a listed path, stop and ask the developer for explicit confirmation. Never self-approve or bypass the gate.

{{HARNESSME_CRITICAL_PATHS}}

## Verified material changes

{{HARNESSME_VERIFIED_CHANGES}}

## Project directives

{{HARNESSME_DIRECTIVES}}

## Keeping this harness current

<!-- HARNESSME:PENDING:START -->
{{HARNESSME_PENDING}}
<!-- HARNESSME:PENDING:END -->`;
}

function operationalReferences() {
  return [{
    slug: "core",
    title: "Core change guide",
    scope: "src/**",
    description: "Read before changing the core service.",
    markdown: "# Core change guide\n\n## Scope\n\n`src/**`\n\n## Responsibilities and invariants\n\n- Keep service behavior in `src/core.ts`. Evidence: `src/core.ts:1`.\n\n## Extension seams\n\n- Extend behavior through `src/core.ts`; call its existing exported interface.\n\n## Invariants\n\n- Preserve the public service contract.\n\n## Change impact\n\n- Update `src/core.ts`, its callers, consumers, and focused tests together.\n\n## Anti-patterns\n\n- Do not duplicate core behavior in callers.\n- Avoid bypassing the exported service interface.\n\n## Workflow\n\n1. Inspect `src/core.ts` and its callers.\n2. Update the service and consumers together.\n3. Run focused tests and `npm test`.\n\n## Validation\n\nRun `npm test`.\n\n## Maintenance triggers\n\nUpdate this guide when a new core extension seam or invariant is introduced.\n",
  }];
}

describe("AI harness authoring", () => {
  it("repairs a reviewed document that omits a required section", async () => {
    let requests = 0;
    let draftSchema: Record<string, unknown> | undefined;
    const server = createServer((request, response) => {
      let body = "";
      request.setEncoding("utf8");
      request.on("data", (chunk) => { body += chunk; });
      request.once("end", () => {
        requests += 1;
        const payload = JSON.parse(body) as { response_format?: { json_schema?: { name?: string; schema?: Record<string, unknown> } } };
        const schema = payload.response_format?.json_schema?.name;
        if (schema === "harnessme_agents_draft") draftSchema = payload.response_format?.json_schema?.schema;
        const result = schema === "harnessme_agents_draft"
          ? { markdown: harnessMarkdown(true), gates: [] }
          : schema === "harnessme_agents_review"
            ? { markdown: harnessMarkdown(false), gates: [], comparison: "The draft was shortened." }
            : { markdown: harnessMarkdown(true), gates: [], comparison: "Restored the required architecture section." };
        response.writeHead(200, { "content-type": "application/json" });
        response.end(JSON.stringify({ choices: [{ message: { content: JSON.stringify(result) } }] }));
      });
    });
    servers.push(server);
    await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
    const address = server.address();
    if (!address || typeof address === "string") throw new Error("Test server did not expose a port.");

    const facts: FactsSnapshot = {
      config: { schemaVersion: 1, targets: ["codex"], languages: [], analysis: { exclude: [], maxFileBytes: 1000 }, distribution: { backend: "native" } },
      conventions: { schemaVersion: 1, generatedAt: new Date().toISOString(), facts: [] },
      stack: { schemaVersion: 1, generatedAt: new Date().toISOString(), languages: [], packageManagers: [], frameworks: [], dependencies: [], topLevelModules: [] },
      evidence: [],
      architecture: "# Observed architecture\n\nNo stable module boundaries were detected.\n",
      directives: "# Project directives\n",
      criticalPaths: { schemaVersion: 1, paths: [], heuristics: { enabled: true, minChanges: 25, minFanIn: 5, minScore: 25 } },
      changes: { schemaVersion: 1, changes: [] },
    };
    const analysis: AnalysisResult = {
      conventions: facts.conventions,
      stack: facts.stack,
      evidence: [],
      architecture: facts.architecture,
      hotspots: [],
      warnings: [],
      sourceFiles: [],
      commands: [],
    };
    const result = await authorHarnessWithAi({
      facts,
      analysis,
      deterministicBaseline: "# Repository instructions\n\n## Observed architecture\n\nNo stable module boundaries were detected.\n",
      inference: {
        enabled: true,
        provider: "http",
        frameworks: [],
        endpoint: `http://127.0.0.1:${address.port}/v1/chat/completions`,
        model: "test-model",
        apiKeyEnv: "",
        maxFiles: 20,
        maxFileBytes: 65_536,
        include: ["**/*"],
        exclude: [],
      },
    });

    expect(result.markdown).toContain("## Repository map");
    expect(result.comparison).toContain("Restored");
    expect(requests).toBe(4);
    const gateItems = (draftSchema?.properties as Record<string, { items?: { required?: string[]; properties?: Record<string, unknown> } }> | undefined)?.gates?.items;
    expect(gateItems?.required).toEqual(["path", "reason", "risk"]);
    expect(gateItems?.properties?.risk).toEqual({
      anyOf: [
        { type: "string", enum: ["security", "persistence", "public-contract", "billing", "deployment", "shared-core", "other"] },
        { type: "null" },
      ],
    });
  });

  it("rejects an inventory report and repairs it into operational instructions", async () => {
    let requests = 0;
    const inventory = harnessMarkdown(true)
      .replace("A repository fixture used to verify harness generation.", "TypeScript (100%).")
      .replace("No stable module boundaries were detected.", "The `src/` module contains `src/core.ts`.")
      .replace("Follow repository-local configuration.", "Preserve the existing service boundary. Evidence: `src/core.ts:1`.")
      .replace("No validation command was detected.", "Run `npm test`.");
    const server = createServer((request, response) => {
      let body = "";
      request.setEncoding("utf8");
      request.on("data", (chunk) => { body += chunk; });
      request.once("end", () => {
        requests += 1;
        const payload = JSON.parse(body) as { response_format?: { json_schema?: { name?: string } } };
        const schema = payload.response_format?.json_schema?.name;
        const result = schema === "harnessme_agents_repair"
          ? { markdown: operationalHarnessMarkdown(), gates: [], references: operationalReferences(), comparison: "Replaced inventory with grounded operating instructions." }
          : schema === "harnessme_agents_review"
            ? { markdown: inventory, gates: [], comparison: "Retained the repository inventory." }
            : { markdown: inventory, gates: [] };
        response.writeHead(200, { "content-type": "application/json" });
        response.end(JSON.stringify({ choices: [{ message: { content: JSON.stringify(result) } }] }));
      });
    });
    servers.push(server);
    await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
    const address = server.address();
    if (!address || typeof address === "string") throw new Error("Test server did not expose a port.");

    const facts: FactsSnapshot = {
      config: { schemaVersion: 1, targets: ["codex"], languages: ["TypeScript"], analysis: { exclude: [], maxFileBytes: 1000 }, distribution: { backend: "native" } },
      conventions: { schemaVersion: 1, generatedAt: new Date().toISOString(), facts: [{ id: "service-boundary", category: "oop", statement: "Preserve the existing service boundary.", confidence: 0.9, evidence: ["core-source"] }] },
      stack: { schemaVersion: 1, generatedAt: new Date().toISOString(), languages: [{ name: "TypeScript", files: 1, percentage: 100 }], packageManagers: ["npm"], frameworks: [], dependencies: [], topLevelModules: ["src"], documentationPaths: ["docs/CORE.md"] },
      evidence: [{ id: "core-source", path: "src/core.ts", line: 1, kind: "ast", excerpt: "export class CoreService" }],
      architecture: "# Observed architecture\n\nThe src module contains the application core.\n",
      directives: "# Project directives\n",
      criticalPaths: { schemaVersion: 1, paths: [], heuristics: { enabled: true, minChanges: 25, minFanIn: 5, minScore: 25 } },
      changes: { schemaVersion: 1, changes: [] },
    };
    const analysis: AnalysisResult = {
      conventions: facts.conventions,
      stack: facts.stack,
      evidence: facts.evidence,
      architecture: facts.architecture,
      hotspots: [],
      warnings: [],
      sourceFiles: ["src/core.ts"],
      commands: ["npm test"],
    };
    const result = await authorHarnessWithAi({
      facts,
      analysis,
      deterministicBaseline: inventory,
      inference: {
        enabled: true,
        provider: "http",
        frameworks: [],
        endpoint: `http://127.0.0.1:${address.port}/v1/chat/completions`,
        model: "test-model",
        apiKeyEnv: "",
        maxFiles: 20,
        maxFileBytes: 65_536,
        include: ["**/*"],
        exclude: [],
      },
    });

    expect(result.markdown).toContain("## Operating rules");
    expect(result.markdown).toContain("## Core boundaries");
    expect(result.markdown).toContain("`docs/CORE.md`");
    expect(result.references).toEqual(expect.arrayContaining([expect.objectContaining({ slug: "core", scope: "src/**" })]));
    expect(result.references[0]?.markdown).toContain("## Responsibilities");
    expect(result.references[0]?.markdown).not.toContain("## Responsibilities and invariants");
    expect(result.references[0]?.markdown).toContain("1. Inspect `src/core.ts` and its callers.");
    expect(result.references[0]?.markdown).toContain("## Extension seams");
    expect(result.references[0]?.markdown).toContain("## Change impact");
    expect(result.references[0]?.markdown).toContain("## Anti-patterns");
    expect(result.references[0]?.markdown).toContain("## Maintenance triggers");
    expect(result.references[0]?.markdown).not.toContain("## Workflow");
    expect(result.markdown).not.toContain("100%");
    expect(requests).toBe(4);
  });
});
