import { join } from "node:path";
import yaml from "js-yaml";
import { atomicWrite, exists, readText } from "./files.js";
import type { CriticalPaths } from "./schema.js";
import { HARNESSME_VERSION } from "./version.js";

const GENERATED_MARKER = "<!-- Generated by HarnessME. Do not edit outside managed sections. -->";
const CODEOWNERS_START = "# HARNESSME:START";
const CODEOWNERS_END = "# HARNESSME:END";

function emptyYamlDocument(source: string): boolean {
  return source.split(/\r?\n/u).every((line) => {
    const trimmed = line.trim();
    return !trimmed || trimmed.startsWith("#") || trimmed === "---" || trimmed === "...";
  });
}

function mapping(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : undefined;
}

export async function renderLefthook(root: string): Promise<string> {
  const relative = "lefthook.yml";
  const path = join(root, relative);
  let config: Record<string, unknown> = {};
  if (await exists(path)) {
    const source = await readText(path);
    let parsed: unknown;
    try {
      parsed = yaml.load(source);
    } catch {
      throw new Error(`Cannot merge HarnessME gate into invalid YAML: ${relative}`);
    }
    if (parsed === undefined || (parsed === null && emptyYamlDocument(source))) {
      // js-yaml represents empty documents as undefined and comment-only documents as null.
      config = {};
    } else if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
      throw new Error(`Cannot merge HarnessME gate into invalid YAML: ${relative}`);
    } else {
      config = parsed as Record<string, unknown>;
    }
  }
  const existingPreCommit = config["pre-commit"];
  if (existingPreCommit !== undefined && existingPreCommit !== null && !mapping(existingPreCommit)) {
    throw new Error(`Cannot merge HarnessME gate into invalid YAML: ${relative}`);
  }
  const preCommit = mapping(existingPreCommit) ?? {};
  const existingCommands = preCommit.commands;
  if (existingCommands !== undefined && existingCommands !== null && !mapping(existingCommands)) {
    throw new Error(`Cannot merge HarnessME gate into invalid YAML: ${relative}`);
  }
  const commands = mapping(existingCommands) ?? {};
  commands.harnessme = { run: "harnessme critical-gate" };
  preCommit.commands = commands;
  config["pre-commit"] = preCommit;
  await atomicWrite(path, yaml.dump(config, { noRefs: true, lineWidth: 100 }));
  return relative;
}

export async function renderHarnessWorkflow(root: string): Promise<string> {
  const relative = ".github/workflows/harnessme.yml";
  const path = join(root, relative);
  const packageSpec = `harnessme@${HARNESSME_VERSION}`;
  const content = [
    `# ${GENERATED_MARKER}`,
    "name: HarnessME",
    "",
    "on:",
    "  pull_request:",
    "  push:",
    "    branches: [main]",
    "  schedule:",
    "    - cron: \"0 6 * * 1\"",
    "",
    "permissions:",
    "  contents: read",
    "",
    "jobs:",
    "  harness:",
    "    runs-on: ubuntu-latest",
    "    steps:",
    "      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4",
    "        with:",
    "          fetch-depth: 0",
    "      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4",
    "        with:",
    "          node-version: 20",
    `      - run: npx --yes ${packageSpec} validate --ci`,
    "      - run: git diff --exit-code",
    `      - run: npx --yes ${packageSpec} check --ci`,
    "      - if: github.event_name == 'pull_request'",
    `        run: npx --yes ${packageSpec} critical-gate --base \"origin/\${{ github.base_ref }}\"`,
    "",
  ].join("\n");
  if (await exists(path)) {
    const existing = await readText(path);
    if (!existing.includes(GENERATED_MARKER)) return relative;
  }
  await atomicWrite(path, content);
  return relative;
}

export async function renderCodeowners(root: string, config: CriticalPaths): Promise<string> {
  const relative = ".github/CODEOWNERS";
  const path = join(root, relative);
  const current = await exists(path) ? await readText(path) : "";
  const start = current.indexOf(CODEOWNERS_START);
  const end = current.indexOf(CODEOWNERS_END);
  const unmanaged = start >= 0 && end > start
    ? `${current.slice(0, start).trimEnd()}\n${current.slice(end + CODEOWNERS_END.length).trimStart()}`
    : current;
  const lines = config.paths.filter((entry) => entry.status === "active").map((entry) =>
    `${entry.glob} ${entry.approvers.map((name) => name.startsWith("@") ? name : `@${name}`).join(" ")}`,
  );
  const managed = `${CODEOWNERS_START}\n${lines.join("\n")}\n${CODEOWNERS_END}`;
  await atomicWrite(path, `${unmanaged.trimEnd()}${unmanaged.trim() ? "\n\n" : ""}${managed}\n`);
  return relative;
}

export async function renderSharedGovernance(root: string, config: CriticalPaths): Promise<string[]> {
  return [await renderLefthook(root), await renderHarnessWorkflow(root), await renderCodeowners(root, config)];
}
