import { join } from "node:path";
import yaml from "js-yaml";
import { atomicWrite, exists, readText } from "./files.js";
import type { CriticalPaths } from "./schema.js";

const GENERATED_MARKER = "<!-- Generated by HarnessME. Do not edit outside managed sections. -->";
const CODEOWNERS_START = "# HARNESSME:START";
const CODEOWNERS_END = "# HARNESSME:END";

export async function renderLefthook(root: string): Promise<string> {
  const relative = "lefthook.yml";
  const path = join(root, relative);
  let config: Record<string, unknown> = {};
  if (await exists(path)) {
    const parsed = yaml.load(await readText(path));
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      throw new Error(`Cannot merge HarnessME gate into invalid YAML: ${relative}`);
    }
    config = parsed as Record<string, unknown>;
  }
  const preCommit = (config["pre-commit"] && typeof config["pre-commit"] === "object"
    ? config["pre-commit"] : {}) as Record<string, unknown>;
  const commands = (preCommit.commands && typeof preCommit.commands === "object"
    ? preCommit.commands : {}) as Record<string, unknown>;
  commands.harnessme = { run: "harnessme critical-gate" };
  preCommit.commands = commands;
  config["pre-commit"] = preCommit;
  await atomicWrite(path, yaml.dump(config, { noRefs: true, lineWidth: 100 }));
  return relative;
}

export async function renderHarnessWorkflow(root: string): Promise<string> {
  const relative = ".github/workflows/harnessme.yml";
  const path = join(root, relative);
  const content = `# ${GENERATED_MARKER}\nname: HarnessME\n\non:\n  pull_request:\n  push:\n    branches: [main]\n  schedule:\n    - cron: \"0 6 * * 1\"\n\npermissions:\n  contents: read\n\njobs:\n  harness:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with:\n          fetch-depth: 0\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npx --yes harnessme@0.1.0 validate --ci\n      - run: git diff --exit-code\n      - run: npx --yes harnessme@0.1.0 check --ci\n      - if: github.event_name == 'pull_request'\n        run: npx --yes harnessme@0.1.0 critical-gate --base \"origin/\${{ github.base_ref }}\"\n`;
  if (await exists(path)) {
    const existing = await readText(path);
    if (!existing.includes(GENERATED_MARKER)) return relative;
  }
  await atomicWrite(path, content);
  return relative;
}

export async function renderCodeowners(root: string, config: CriticalPaths): Promise<string> {
  const relative = ".github/CODEOWNERS";
  const path = join(root, relative);
  const current = await exists(path) ? await readText(path) : "";
  const start = current.indexOf(CODEOWNERS_START);
  const end = current.indexOf(CODEOWNERS_END);
  const unmanaged = start >= 0 && end > start
    ? `${current.slice(0, start).trimEnd()}\n${current.slice(end + CODEOWNERS_END.length).trimStart()}`
    : current;
  const lines = config.paths.map((entry) =>
    `${entry.glob} ${entry.approvers.map((name) => name.startsWith("@") ? name : `@${name}`).join(" ")}`,
  );
  const managed = `${CODEOWNERS_START}\n${lines.join("\n")}\n${CODEOWNERS_END}`;
  await atomicWrite(path, `${unmanaged.trimEnd()}${unmanaged.trim() ? "\n\n" : ""}${managed}\n`);
  return relative;
}

export async function renderSharedGovernance(root: string, config: CriticalPaths): Promise<string[]> {
  return [await renderLefthook(root), await renderHarnessWorkflow(root), await renderCodeowners(root, config)];
}
