import { createHash } from "node:crypto";
import { minimatch } from "minimatch";
import {
  FeatureOverridesSchema,
  FeatureDefinitionSchema,
  KnowledgeGraphSchema,
  type CriticalPaths,
  type FeatureDefinition,
  type FeatureOverrides,
  type FeaturePack,
  type KnowledgeEdge,
  type KnowledgeGraph,
  type KnowledgeNode,
  type ReferencePack,
  type RepositoryStructure,
} from "./schema.js";

const GENERATED_MARKER = "<!-- Generated by HarnessME. Do not edit. -->";

export interface KnowledgeArtifactsInput {
  structure: RepositoryStructure;
  features: FeaturePack;
  references?: ReferencePack;
  criticalPaths: CriticalPaths;
  overrides?: FeatureOverrides;
  referenceProvenance?: "deterministic" | "ai-reviewed";
}

export interface KnowledgeArtifacts {
  graph: KnowledgeGraph;
  documents: Array<{ path: string; markdown: string }>;
  diagnostics: KnowledgeGraph["diagnostics"];
}

function safePath(path: string): boolean {
  return Boolean(path) && !path.startsWith("/") && !/^[A-Za-z]:\//u.test(path) && !path.split("/").includes("..");
}

function moduleOf(path: string): string | undefined {
  const first = path.split("/")[0];
  return path.includes("/") && first && !first.startsWith(".") ? first : undefined;
}

function featureId(feature: Pick<FeatureDefinition, "kind" | "slug">): string {
  return `${feature.kind}:${feature.slug}`;
}

function edgeId(kind: KnowledgeEdge["kind"], from: string, to: string): string {
  return `${kind}:${from}->${to}`;
}

function criticalId(glob: string): string {
  return `critical:${createHash("sha256").update(glob).digest("hex").slice(0, 12)}`;
}

function matches(path: string, scope: string): boolean {
  const normalized = scope.endsWith("/") ? `${scope}**` : scope;
  return path === scope.replace(/\/$/u, "") || minimatch(path, normalized, { dot: true });
}

function sectionItems(markdown: string, heading: string): string[] {
  const body = markdown.match(new RegExp(`^## ${heading}\\s*$([\\s\\S]*?)(?=^## |$(?![\\s\\S]))`, "mu"))?.[1]?.trim() ?? "";
  const bullets = body.split(/\r?\n/u).map((line) => line.match(/^\s*(?:[-*]|\d+\.)\s+(.+)$/u)?.[1]).filter((item): item is string => Boolean(item));
  return bullets.length ? bullets : body ? [body.replace(/\s+/gu, " ")] : [];
}

function featureFromReference(reference: ReferencePack["documents"][number], structure: RepositoryStructure): FeatureDefinition | undefined {
  const required = ["Responsibilities", "Invariants", "Validation"];
  if (!required.every((heading) => reference.markdown.includes(`## ${heading}`))) return undefined;
  const known = new Set([...structure.files.map((item) => item.path), ...structure.documents]);
  const citations = [...reference.markdown.matchAll(/`([^`\n]+):(\d+)`/gu)]
    .map((match) => ({ path: match[1]!, line: Number(match[2]) }))
    .filter((citation, index, all) => safePath(citation.path) && known.has(citation.path)
      && all.findIndex((item) => item.path === citation.path && item.line === citation.line) === index);
  if (!citations.length) return undefined;
  const scopes = (reference.scopes ?? [reference.scope]).map((scope) => scope.endsWith("/") ? `${scope}**` : scope);
  if (!scopes.some((scope) => structure.files.some((file) => matches(file.path, scope)))) return undefined;
  return FeatureDefinitionSchema.parse({
    slug: reference.slug,
    kind: "concern",
    title: reference.title,
    summary: reference.description,
    scopes,
    responsibilities: sectionItems(reference.markdown, "Responsibilities").slice(0, 20),
    invariants: sectionItems(reference.markdown, "Invariants").slice(0, 20),
    validation: sectionItems(reference.markdown, "Validation").slice(0, 20),
    citations,
    relationships: [],
  });
}

function scopesOverlap(left: string, right: string): boolean {
  const exactLeft = !left.includes("*");
  const exactRight = !right.includes("*");
  if (exactLeft && exactRight) return left.replace(/\/$/u, "") === right.replace(/\/$/u, "");
  const leftBase = left.replace(/\*.*$/u, "").replace(/\/$/u, "");
  const rightBase = right.replace(/\*.*$/u, "").replace(/\/$/u, "");
  if (!leftBase || !rightBase) return false;
  const wildcardBase = exactLeft ? rightBase : leftBase;
  if (wildcardBase.split("/").filter(Boolean).length < 2) return false;
  return matches(leftBase, right) || matches(rightBase, left)
    || leftBase.startsWith(`${rightBase}/`) || rightBase.startsWith(`${leftBase}/`);
}

function bullets(values: string[], empty: string): string {
  return values.length ? values.map((value) => `- ${value}`).join("\n") : `- ${empty}`;
}

function renderFeatureGuide(feature: FeatureDefinition, graph: KnowledgeGraph): string {
  const id = featureId(feature);
  const outgoing = graph.edges.filter((edge) => edge.from === id);
  const incoming = graph.edges.filter((edge) => edge.to === id);
  const nodes = new Map(graph.nodes.map((node) => [node.id, node]));
  const targets = (kind: KnowledgeEdge["kind"]): string[] => outgoing
    .filter((edge) => edge.kind === kind)
    .map((edge) => nodes.get(edge.to))
    .filter((node): node is KnowledgeNode => Boolean(node))
    .map((node) => node.path ? `\`${node.path}\`` : node.label);
  const dependencies = targets("depends-on");
  const consumers = incoming.filter((edge) => edge.kind === "depends-on")
    .map((edge) => nodes.get(edge.from)?.label).filter((value): value is string => Boolean(value));
  const citations = feature.citations.map((citation) => `\`${citation.path}:${citation.line}\``);
  return `${GENERATED_MARKER}
# ${feature.title}

## Purpose

${feature.summary}

## Responsibilities

${bullets(feature.responsibilities, "Use the scoped implementation paths as the source of truth.")}

## Where it lives

${bullets(feature.scopes.map((scope) => `\`${scope}\``), "No implementation scope is registered.")}

## Invariants

${bullets(feature.invariants, "Preserve the existing contracts demonstrated by callers and tests.")}

## Dependencies

${bullets(dependencies, "No feature dependency is recorded.")}

## Change impact

${bullets(consumers, "No dependent feature is recorded; still inspect file-level importers before editing.")}

## Tests and validation

${bullets([...feature.validation, ...targets("verified-by")], "Run the repository's validated checks and inspect nearby tests.")}

## Critical paths

${bullets(targets("protected-by"), "No active critical path intersects this feature.")}

## Evidence

${bullets(citations, feature.citations.length ? "" : "Maintainer-declared or deterministically derived; no semantic citation is recorded.")}

## Agent support

- Graph node: \`${id}\`.
- Implementation: ${targets("implements").join(", ") || "no matched source files"}.
- Documentation: ${targets("documented-by").join(", ") || "this generated guide"}.
- Before editing, inspect this node's incoming and outgoing relationships in \`.harnessme/knowledge-graph.json\`.
`;
}

function renderIndex(graph: KnowledgeGraph, features: FeatureDefinition[]): string {
  const modules = graph.nodes.filter((node) => node.kind === "module");
  const diagnostics = graph.diagnostics.length
    ? graph.diagnostics.map((item) => `- ${item.severity.toUpperCase()}: ${item.message}`).join("\n")
    : "- No graph diagnostics.";
  const rows = features.map((feature) => {
    const id = featureId(feature);
    const deps = graph.edges.filter((edge) => edge.from === id && edge.kind === "depends-on")
      .map((edge) => graph.nodes.find((node) => node.id === edge.to)?.label).filter(Boolean).join(", ") || "—";
    return `| [${feature.title}](features/${feature.slug}.md) | ${feature.kind} | ${feature.scopes.map((scope) => `\`${scope}\``).join(", ")} | ${deps} |`;
  });
  return `${GENERATED_MARKER}
# Feature navigation

Use this map before a behavior-level or cross-module edit. Open the smallest relevant feature guide, inspect its implementation paths and tests, then trace dependencies in \`.harnessme/knowledge-graph.json\`.

## Features and concerns

${rows.length ? `| Name | Kind | Scope | Depends on |\n|---|---|---|---|\n${rows.join("\n")}` : "No semantic feature has been declared. Use the module map below or add one with `harnessme feature add`."}

## Module map

${bullets(modules.map((node) => `\`${node.path ?? node.label}\``), "No source module was detected.")}

## Graph health

${diagnostics}
`;
}

export function validateKnowledgeGraph(graph: KnowledgeGraph): KnowledgeGraph {
  const parsed = KnowledgeGraphSchema.parse(graph);
  const ids = new Set<string>();
  const knownPaths = new Set(parsed.nodes.flatMap((node) => node.path ? [node.path] : []));
  for (const node of parsed.nodes) {
    if (ids.has(node.id)) throw new Error(`Duplicate knowledge-graph node: ${node.id}`);
    ids.add(node.id);
    if ((node.path && !safePath(node.path)) || (node.guide && !safePath(node.guide))) throw new Error(`Unsafe knowledge-graph path on ${node.id}`);
    const idPrefix = node.kind === "critical-path" ? "critical" : node.kind;
    if (!node.id.startsWith(`${idPrefix}:`)) throw new Error(`Knowledge-graph node ID does not match its kind: ${node.id}`);
    if (node.guide && (!['feature', 'concern'].includes(node.kind) || !/^\.harnessme\/features\/[^/]+\.md$/u.test(node.guide))) throw new Error(`Invalid knowledge-graph guide on ${node.id}`);
    if (node.provenance === "ai-reviewed" && ["feature", "concern"].includes(node.kind) && !node.citations.length) throw new Error(`AI-reviewed graph node lacks evidence: ${node.id}`);
    if (node.citations.some((citation) => !safePath(citation.path))) throw new Error(`Unsafe knowledge-graph citation on ${node.id}`);
    if (node.citations.some((citation) => !knownPaths.has(citation.path))) throw new Error(`Knowledge-graph node cites an unknown path: ${node.id}`);
  }
  const edgeIds = new Set<string>();
  for (const edge of parsed.edges) {
    if (edgeIds.has(edge.id)) throw new Error(`Duplicate knowledge-graph edge: ${edge.id}`);
    edgeIds.add(edge.id);
    if (!ids.has(edge.from) || !ids.has(edge.to)) throw new Error(`Knowledge-graph edge has a missing endpoint: ${edge.id}`);
    if (edge.from === edge.to && edge.kind !== "related-to") throw new Error(`Knowledge-graph edge cannot target itself: ${edge.id}`);
    if (edge.id !== edgeId(edge.kind, edge.from, edge.to)) throw new Error(`Knowledge-graph edge ID is not canonical: ${edge.id}`);
    if (edge.provenance === "ai-reviewed" && ["depends-on", "related-to"].includes(edge.kind) && !edge.citations.length) throw new Error(`AI-reviewed graph relationship lacks evidence: ${edge.id}`);
    if (edge.citations.some((citation) => !safePath(citation.path))) throw new Error(`Unsafe knowledge-graph citation on ${edge.id}`);
    if (edge.citations.some((citation) => !knownPaths.has(citation.path))) throw new Error(`Knowledge-graph edge cites an unknown path: ${edge.id}`);
  }
  return parsed;
}

export function createKnowledgeArtifacts(input: KnowledgeArtifactsInput): KnowledgeArtifacts {
  const overrides = FeatureOverridesSchema.parse(input.overrides ?? { schemaVersion: 1 });
  const excluded = new Set(overrides.excludedFeatures);
  const featureMap = new Map<string, FeatureDefinition>();
  const provenance = new Map<string, KnowledgeNode["provenance"]>();
  for (const feature of input.features.features) {
    if (!excluded.has(feature.slug) && !excluded.has(featureId(feature))) {
      featureMap.set(feature.slug, feature);
      provenance.set(feature.slug, "ai-reviewed");
    }
  }
  for (const reference of input.references?.documents ?? []) {
    if (featureMap.has(reference.slug) || excluded.has(reference.slug) || excluded.has(`concern:${reference.slug}`)) continue;
    const derived = featureFromReference(reference, input.structure);
    if (derived) {
      featureMap.set(derived.slug, derived);
      provenance.set(derived.slug, input.referenceProvenance ?? "ai-reviewed");
    }
  }
  for (const override of overrides.features) {
    if (excluded.has(override.slug) || excluded.has(`feature:${override.slug}`) || excluded.has(`concern:${override.slug}`)) continue;
    const existing = featureMap.get(override.slug);
    featureMap.set(override.slug, FeatureDefinitionSchema.parse(existing ? { ...existing, ...override } : override));
    provenance.set(override.slug, "maintainer");
  }
  const features = [...featureMap.values()].sort((a, b) => a.slug.localeCompare(b.slug));
  const diagnostics: KnowledgeGraph["diagnostics"] = [];
  const nodes = new Map<string, KnowledgeNode>();
  const edges = new Map<string, KnowledgeEdge>();
  const addNode = (node: KnowledgeNode): void => { nodes.set(node.id, node); };
  const addEdge = (edge: Omit<KnowledgeEdge, "id">): void => {
    const id = edgeId(edge.kind, edge.from, edge.to);
    const shortId = `${edge.kind}:${edge.from.replace(/^[^:]+:/u, "")}->${edge.to.replace(/^[^:]+:/u, "")}`;
    if (overrides.excludedRelationships.includes(id) || overrides.excludedRelationships.includes(shortId)) return;
    const existing = edges.get(id);
    if (existing) {
      existing.weight = (existing.weight ?? 1) + (edge.weight ?? 1);
      existing.citations = [...existing.citations, ...edge.citations].filter((item, index, all) => all.findIndex((other) => other.path === item.path && other.line === item.line) === index);
      if (edge.provenance === "maintainer" || (edge.provenance === "deterministic" && existing.provenance === "ai-reviewed")) existing.provenance = edge.provenance;
    } else edges.set(id, { ...edge, id });
  };

  for (const item of input.structure.files) {
    const module = item.module ?? moduleOf(item.path);
    const nodeKind = item.kind === "source" ? "file" as const : "test" as const;
    const id = `${nodeKind}:${item.path}`;
    addNode({ id, kind: nodeKind, label: item.path.split("/").at(-1) ?? item.path, path: item.path, provenance: "deterministic", citations: [{ path: item.path, line: 1 }] });
    if (module) {
      const moduleId = `module:${module}`;
      addNode({ id: moduleId, kind: "module", label: module, path: `${module}/`, provenance: "deterministic", citations: [] });
      addEdge({ from: moduleId, to: id, kind: "contains", provenance: "deterministic", citations: [{ path: item.path, line: 1 }] });
    }
  }
  for (const item of input.structure.imports) {
    const from = `${input.structure.files.find((file) => file.path === item.from)?.kind === "test" ? "test" : "file"}:${item.from}`;
    const to = `${input.structure.files.find((file) => file.path === item.to)?.kind === "test" ? "test" : "file"}:${item.to}`;
    if (!nodes.has(from) || !nodes.has(to)) continue;
    addEdge({ from, to, kind: "imports", provenance: "deterministic", citations: [{ path: item.from, line: item.line }] });
    const fromModule = input.structure.files.find((file) => file.path === item.from)?.module ?? moduleOf(item.from);
    const toModule = input.structure.files.find((file) => file.path === item.to)?.module ?? moduleOf(item.to);
    if (fromModule && toModule && fromModule !== toModule) {
      addEdge({ from: `module:${fromModule}`, to: `module:${toModule}`, kind: "depends-on", provenance: "deterministic", weight: 1, citations: [{ path: item.from, line: item.line }] });
    }
  }
  for (const reference of input.references?.documents ?? []) {
    const path = `.harnessme/references/${reference.slug}.md`;
    addNode({ id: `document:${path}`, kind: "document", label: reference.title, path, provenance: "deterministic", citations: [] });
  }
  for (const path of input.structure.documents) {
    addNode({ id: `document:${path}`, kind: "document", label: path.split("/").at(-1) ?? path, path, provenance: "deterministic", citations: [{ path, line: 1 }] });
  }
  for (const rule of input.criticalPaths.paths.filter((item) => item.status === "active")) {
    addNode({ id: criticalId(rule.glob), kind: "critical-path", label: rule.glob, scope: rule.glob, summary: rule.reason, provenance: rule.source === "ai-reviewed" ? "ai-reviewed" : rule.source === "explicit" ? "maintainer" : "deterministic", citations: [] });
  }
  for (const feature of features) {
    const id = featureId(feature);
    const guide = `.harnessme/features/${feature.slug}.md`;
    addNode({ id, kind: feature.kind, label: feature.title, summary: feature.summary, guide, provenance: provenance.get(feature.slug) ?? "ai-reviewed", citations: feature.citations });
    addNode({ id: `document:${guide}`, kind: "document", label: `${feature.title} guide`, path: guide, provenance: "deterministic", citations: [] });
    addEdge({ from: id, to: `document:${guide}`, kind: "documented-by", provenance: "deterministic", citations: [] });
    const matched = input.structure.files.filter((file) => feature.scopes.some((scope) => matches(file.path, scope)));
    if (!matched.length) diagnostics.push({ severity: "error", code: "empty-feature-scope", message: `${feature.title} has no matching repository files.` });
    for (const file of matched) {
      addEdge({ from: id, to: `${file.kind === "test" ? "test" : "file"}:${file.path}`, kind: file.kind === "test" ? "verified-by" : "implements", provenance: provenance.get(feature.slug) ?? "ai-reviewed", citations: feature.citations });
    }
    const implementationPaths = new Set(matched.filter((file) => file.kind === "source").map((file) => file.path));
    for (const item of input.structure.imports) {
      const test = input.structure.files.find((file) => file.path === item.from && file.kind === "test");
      if (test && implementationPaths.has(item.to)) addEdge({ from: id, to: `test:${test.path}`, kind: "verified-by", provenance: "deterministic", citations: [{ path: item.from, line: item.line }] });
    }
    for (const relation of feature.relationships) {
      const target = features.find((candidate) => candidate.slug === relation.to);
      if (!target && (excluded.has(relation.to) || excluded.has(`feature:${relation.to}`) || excluded.has(`concern:${relation.to}`))) continue;
      if (!target) {
        diagnostics.push({ severity: "error", code: "missing-feature-target", message: `${feature.title} relates to missing feature ${relation.to}.` });
        continue;
      }
      addEdge({ from: id, to: featureId(target), kind: relation.kind, provenance: provenance.get(feature.slug) ?? "ai-reviewed", citations: relation.citations });
    }
    for (const reference of input.references?.documents ?? []) {
      const scopes = reference.scopes ?? [reference.scope];
      if (feature.slug === reference.slug || feature.scopes.some((scope) => scopes.some((candidate) => scopesOverlap(scope, candidate)))) {
        addEdge({ from: id, to: `document:.harnessme/references/${reference.slug}.md`, kind: "documented-by", provenance: "deterministic", citations: [] });
      }
    }
    for (const path of input.structure.documents) {
      if (feature.scopes.some((scope) => path === scope || path.startsWith(scope.replace(/\*.*$/u, "")))) addEdge({ from: id, to: `document:${path}`, kind: "documented-by", provenance: "deterministic", citations: [{ path, line: 1 }] });
    }
  }
  for (const relation of overrides.relationships) {
    const from = features.find((item) => item.slug === relation.from);
    const to = features.find((item) => item.slug === relation.to);
    if (!from || !to) {
      diagnostics.push({ severity: "error", code: "missing-override-target", message: `Maintainer relationship ${relation.from} -> ${relation.to} has a missing endpoint.` });
      continue;
    }
    addEdge({ from: featureId(from), to: featureId(to), kind: relation.kind, provenance: "maintainer", citations: [] });
  }
  const fileNodes = [...nodes.values()].filter((node) => node.kind === "file" || node.kind === "test");
  const criticalNodes = [...nodes.values()].filter((node) => node.kind === "critical-path");
  for (const node of fileNodes) {
    for (const critical of criticalNodes) {
      if (node.path && critical.scope && matches(node.path, critical.scope)) addEdge({ from: node.id, to: critical.id, kind: "protected-by", provenance: "deterministic", citations: [{ path: node.path, line: 1 }] });
    }
  }
  for (const feature of features) {
    const id = featureId(feature);
    const protectedTargets = [...edges.values()].filter((edge) => edge.from === id && edge.kind === "implements")
      .flatMap((edge) => [...edges.values()].filter((candidate) => candidate.from === edge.to && candidate.kind === "protected-by"));
    for (const protectedEdge of protectedTargets) addEdge({ from: id, to: protectedEdge.to, kind: "protected-by", provenance: "deterministic", citations: protectedEdge.citations });
  }
  if (features.length) {
    const covered = new Set([...edges.values()].filter((edge) => edge.kind === "implements" || edge.kind === "verified-by").map((edge) => edge.to));
    const orphaned = fileNodes.filter((node) => !covered.has(node.id));
    if (orphaned.length) diagnostics.push({ severity: "warning", code: "orphaned-files", message: `${orphaned.length} analyzed file(s) are not assigned to a feature or concern.` });
  }
  const featureProvenance = new Set(features.map((item) => provenance.get(item.slug) ?? "ai-reviewed"));
  const generation = featureProvenance.has("maintainer")
    ? "mixed" as const
    : featureProvenance.has("ai-reviewed") ? "ai-reviewed" as const : "deterministic" as const;
  const failures = diagnostics.filter((item) => item.severity === "error");
  if (failures.length) throw new Error(`Invalid feature graph:\n${failures.map((item) => `- ${item.message}`).join("\n")}`);
  const graph = validateKnowledgeGraph({ schemaVersion: 1, generatedAt: input.structure.generatedAt, generation, nodes: [...nodes.values()].sort((a, b) => a.id.localeCompare(b.id)), edges: [...edges.values()].sort((a, b) => a.id.localeCompare(b.id)), diagnostics });
  const documents = [
    { path: ".harnessme/FEATURES.md", markdown: renderIndex(graph, features) },
    ...features.map((feature) => ({ path: `.harnessme/features/${feature.slug}.md`, markdown: renderFeatureGuide(feature, graph) })),
  ];
  return { graph, documents, diagnostics };
}
