import { join } from "node:path";
import { exists, harnessDir, readFacts, readText } from "@harnessme/core";

export interface DashboardState {
  initialized: boolean;
  repository: string;
  quality: string;
  mode: string;
  provider: string;
  model: string;
  activeGates: number;
  proposedGates: number;
  references: number;
  preview: string[];
}

export async function loadDashboardState(root: string): Promise<DashboardState> {
  const initialized = await exists(harnessDir(root));
  if (!initialized) return {
    initialized,
    repository: root,
    quality: "—",
    mode: "not initialized",
    provider: "—",
    model: "—",
    activeGates: 0,
    proposedGates: 0,
    references: 0,
    preview: ["No harness exists in this repository.", "", "Choose Initialize to analyze it."],
  };
  const facts = await readFacts(root);
  const inference = facts.config.analysis.aiFallback;
  const agentsPath = join(root, "AGENTS.md");
  const preview = await exists(agentsPath)
    ? (await readText(agentsPath)).split(/\r?\n/u).filter((line) => !line.startsWith("<!-- Generated by HarnessME")).slice(0, 80)
    : ["AGENTS.md has not been rendered."];
  return {
    initialized,
    repository: root,
    quality: facts.quality ? `${facts.quality.score}/100` : "not measured",
    mode: facts.generation?.status ?? (inference ? "AI configured" : "deterministic"),
    provider: inference?.provider ?? "deterministic",
    model: inference?.model ?? "provider default",
    activeGates: facts.criticalPaths.paths.filter((item) => item.status === "active").length,
    proposedGates: facts.criticalPaths.paths.filter((item) => item.status === "proposed").length,
    references: facts.referencePack?.documents.length ?? 0,
    preview,
  };
}
