import { readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import { assessHarnessQuality, exists, harnessDir, readFacts, readText, type HarnessQuality } from "@harnessme/core";

const GENERATED_MARKER = "<!-- Generated by HarnessME";

export interface DashboardDocument {
  label: string;
  path: string;
  content: string[];
}

export interface DashboardState {
  initialized: boolean;
  repository: string;
  quality?: HarnessQuality;
  mode: string;
  provider: string;
  model: string;
  thinking: string;
  activeGates: number;
  proposedGates: number;
  references: number;
  graphNodes: number;
  graphEdges: number;
  documents: DashboardDocument[];
}

function previewLines(markdown: string): string[] {
  return markdown
    .split(/\r?\n/u)
    .filter((line) => !line.startsWith(GENERATED_MARKER))
    .slice(0, 120);
}

async function addDocument(documents: DashboardDocument[], root: string, label: string, path: string): Promise<void> {
  const absolutePath = join(root, path);
  if (!await exists(absolutePath)) return;
  documents.push({ label, path, content: previewLines(await readText(absolutePath)) });
}

async function generatedNestedAgents(root: string, directory = root): Promise<string[]> {
  const documents: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink() || [".git", ".harnessme", ".ruler", "node_modules"].includes(entry.name)) continue;
    const path = join(directory, entry.name);
    if (entry.isDirectory()) documents.push(...await generatedNestedAgents(root, path));
    else if (entry.name === "AGENTS.md" && directory !== root && (await readText(path)).startsWith(GENERATED_MARKER)) documents.push(relative(root, path));
  }
  return documents;
}

export async function loadDashboardState(root: string): Promise<DashboardState> {
  const initialized = await exists(harnessDir(root));
  if (!initialized) return {
    initialized,
    repository: root,
    quality: undefined,
    mode: "not initialized",
    provider: "—",
    model: "—",
    thinking: "—",
    activeGates: 0,
    proposedGates: 0,
    references: 0,
    graphNodes: 0,
    graphEdges: 0,
    documents: [{
      label: "Getting started",
      path: "",
      content: ["No harness exists in this repository.", "", "Choose Initialize to analyze it."],
    }],
  };
  const facts = await readFacts(root);
  // Keep the dashboard honest: this is the same live assessment used by the
  // dedicated Quality page, rather than the score saved during a past refresh.
  const quality = assessHarnessQuality(
    facts,
    facts.documentationConflicts ?? [],
    await readText(join(root, "AGENTS.md")),
  );
  const inference = facts.config.analysis.aiFallback;
  const documents: DashboardDocument[] = [];
  await addDocument(documents, root, "Root AGENTS", "AGENTS.md");
  await addDocument(documents, root, "AI authored", ".harnessme/facts/AGENTS.authored.md");
  await addDocument(documents, root, "Critical paths", ".harnessme/CRITICAL.md");
  await addDocument(documents, root, "Feature map", ".harnessme/FEATURES.md");
  for (const reference of facts.referencePack?.documents ?? []) {
    await addDocument(documents, root, `Guide · ${reference.slug}`, `.harnessme/references/${reference.slug}.md`);
  }
  for (const name of ["architecture", "testing-and-validation", "critical-change-audit"]) {
    await addDocument(documents, root, `Pack · ${name}`, `.harnessme/agent-pack/${name}.md`);
  }
  for (const path of await generatedNestedAgents(root)) {
    const directory = path.slice(0, -"/AGENTS.md".length) || ".";
    await addDocument(documents, root, `Module · ${directory}`, path);
  }
  if (!documents.length) documents.push({ label: "Root AGENTS", path: "AGENTS.md", content: ["AGENTS.md has not been rendered."] });
  return {
    initialized,
    repository: root,
    quality,
    mode: facts.generation?.status ?? (inference ? "AI configured" : "deterministic"),
    provider: inference?.provider ?? "deterministic",
    model: inference?.model ?? "provider default",
    thinking: inference?.reasoningEffort ?? "provider default",
    activeGates: facts.criticalPaths.paths.filter((item) => item.status === "active").length,
    proposedGates: facts.criticalPaths.paths.filter((item) => item.status === "proposed").length,
    references: facts.referencePack?.documents.length ?? 0,
    graphNodes: facts.knowledgeGraph?.nodes.length ?? 0,
    graphEdges: facts.knowledgeGraph?.edges.length ?? 0,
    documents,
  };
}
