import type { KnowledgeGraph } from "@harnessme/core";

function safeJson(value: unknown): string {
  return JSON.stringify(value).replaceAll("<", "\\u003c").replaceAll("\u2028", "\\u2028").replaceAll("\u2029", "\\u2029");
}

/** Render a dependency-free, portable 3D force graph that works from file://. */
export function renderForceGraphHtml(graph: KnowledgeGraph): string {
  const data = safeJson(graph);
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>HarnessME · 3D Knowledge Graph</title>
<style>
:root{color-scheme:dark;font:14px Inter,ui-sans-serif,system-ui,sans-serif;background:#070b16;color:#e2e8f0}*{box-sizing:border-box}body{margin:0;overflow:hidden}canvas{position:fixed;inset:0;width:100vw;height:100vh;cursor:grab}canvas.drag{cursor:grabbing}.top{position:fixed;top:16px;left:16px;right:16px;display:flex;gap:10px;align-items:center;z-index:2;pointer-events:none}.brand,.controls,.legend,.panel{background:#0b1020dc;border:1px solid #263755;box-shadow:0 14px 36px #0008;backdrop-filter:blur(12px);border-radius:12px}.brand{padding:10px 14px}.brand b{color:#67e8f9}.brand small{display:block;color:#94a3b8}.controls{padding:8px;display:flex;gap:7px;pointer-events:auto;flex:1;max-width:720px}input,select,button{border:1px solid #334155;background:#111a2e;color:#e2e8f0;border-radius:8px;padding:7px 9px}input{flex:1;min-width:130px}button{cursor:pointer}button:hover{border-color:#22d3ee}.panel{position:fixed;right:16px;top:86px;width:min(360px,calc(100vw - 32px));max-height:calc(100vh - 150px);overflow:auto;padding:16px;z-index:2}.panel h2{font-size:18px;margin:0 0 5px}.muted{color:#94a3b8}.badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#17233b;margin:2px 3px 2px 0;font-size:12px}.section{border-top:1px solid #263755;margin-top:12px;padding-top:10px}.section b{color:#67e8f9}.links a{display:block;color:#93c5fd;text-decoration:none;margin:5px 0}.links a:hover{text-decoration:underline}.legend{position:fixed;left:16px;bottom:16px;padding:10px 12px;z-index:2;display:flex;gap:10px;flex-wrap:wrap;max-width:calc(100vw - 32px)}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:5px}.hint{position:fixed;right:16px;bottom:16px;color:#64748b;z-index:2}@media(max-width:850px){.top{flex-wrap:wrap}.panel{top:142px}.hint{display:none}.brand small{display:none}}
</style></head><body>
<canvas id="scene"></canvas><div class="top"><div class="brand"><b>HarnessME · 3D Graph</b><small id="stats"></small></div><div class="controls"><input id="search" placeholder="Search feature, file, guide…"><select id="kind"><option value="all">All node kinds</option></select><select id="depth"><option value="0">Whole graph</option><option value="1">1-hop focus</option><option value="2">2-hop focus</option><option value="3">3-hop focus</option></select><button id="reset">Reset</button><button id="spin">Pause spin</button></div></div>
<aside class="panel" id="panel"><h2>Explore the graph</h2><div class="muted">Click a node to inspect evidence and connections. Drag to rotate, scroll to zoom, double-click to center.</div></aside><div class="legend" id="legend"></div><div class="hint">Drag rotate · Wheel zoom · Click inspect · Double-click focus</div>
<script>"use strict";
const graph=${data};
const colors={feature:"#22d3ee",concern:"#a78bfa",module:"#fbbf24",file:"#60a5fa",test:"#4ade80",document:"#f472b6","critical-path":"#fb7185"};
const canvas=document.getElementById("scene"),ctx=canvas.getContext("2d"),panel=document.getElementById("panel"),search=document.getElementById("search"),kind=document.getElementById("kind"),depth=document.getElementById("depth");
const byId=new Map(graph.nodes.map(function(n){return[n.id,n]})),adj=new Map(graph.nodes.map(function(n){return[n.id,[]]}));graph.edges.forEach(function(e){if(adj.has(e.from)&&adj.has(e.to)){adj.get(e.from).push({id:e.to,edge:e,out:true});adj.get(e.to).push({id:e.from,edge:e,out:false})}});
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}function seeded(s){return((hash(s)%10000)/10000)*2-1}
const nodes=graph.nodes.map(function(n,i){const a=(i/Math.max(1,graph.nodes.length))*Math.PI*2,r=130+Math.abs(seeded(n.id))*180;return Object.assign({},n,{x:Math.cos(a)*r,y:Math.sin(a)*r,z:seeded(n.id+"z")*220,vx:0,vy:0,vz:0,degree:(adj.get(n.id)||[]).length})});const simById=new Map(nodes.map(function(n){return[n.id,n]}));
let yaw=.3,pitch=-.18,zoom=1,drag=false,lastX=0,lastY=0,selected=null,hover=null,spinning=true,settle=0,visible=new Set(nodes.map(function(n){return n.id}));
function resize(){const d=Math.min(2,devicePixelRatio||1);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);resize();
function project(n){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=n.x*cy-n.z*sy,z1=n.x*sy+n.z*cy,y=n.y*cp-z1*sp,z=n.y*sp+z1*cp,d=760/(760+z);return{x:innerWidth/2+x*d*zoom,y:innerHeight/2+y*d*zoom,z:z,d:d}}
function updateVisible(){const q=search.value.trim().toLowerCase(),k=kind.value;let base=nodes.filter(function(n){return(k==="all"||n.kind===k)&&(!q||(n.label+" "+n.id+" "+(n.path||"")).toLowerCase().includes(q))});const hops=Number(depth.value);if(hops&&selected){const seen=new Set([selected.id]);let front=[selected.id];for(let d=0;d<hops;d++){const next=[];front.forEach(function(id){(adj.get(id)||[]).forEach(function(a){if(!seen.has(a.id)){seen.add(a.id);next.push(a.id)}})});front=next}base=nodes.filter(function(n){return seen.has(n.id)&&(k==="all"||n.kind===k)&&(!q||(n.label+" "+n.id+" "+(n.path||"")).toLowerCase().includes(q))})}visible=new Set(base.map(function(n){return n.id}));document.getElementById("stats").textContent=visible.size+" / "+nodes.length+" nodes · "+graph.edges.length+" edges · "+graph.generation}
function simulate(){if(settle>900)return;const active=nodes.filter(function(n){return visible.has(n.id)}),limit=22000;let pairs=0;for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length&&pairs++<limit;j++){const a=active[i],b=active[j],dx=a.x-b.x,dy=a.y-b.y,dz=a.z-b.z,d2=dx*dx+dy*dy+dz*dz+40,f=500/d2;a.vx+=dx*f;a.vy+=dy*f;a.vz+=dz*f;b.vx-=dx*f;b.vy-=dy*f;b.vz-=dz*f}graph.edges.forEach(function(e){if(!visible.has(e.from)||!visible.has(e.to))return;const a=simById.get(e.from),b=simById.get(e.to);if(!a||!b)return;const dx=b.x-a.x,dy=b.y-a.y,dz=b.z-a.z,dist=Math.sqrt(dx*dx+dy*dy+dz*dz)||1,f=(dist-95)*.0007*(e.weight||1);a.vx+=dx*f;a.vy+=dy*f;a.vz+=dz*f;b.vx-=dx*f;b.vy-=dy*f;b.vz-=dz*f});active.forEach(function(n){n.vx+=-n.x*.00025;n.vy+=-n.y*.00025;n.vz+=-n.z*.00025;n.vx*=.88;n.vy*=.88;n.vz*=.88;n.x+=n.vx;n.y+=n.vy;n.z+=n.vz});settle++}
function draw(){requestAnimationFrame(draw);if(spinning&&!drag)yaw+=.0008;simulate();ctx.clearRect(0,0,innerWidth,innerHeight);const projected=new Map(nodes.filter(function(n){return visible.has(n.id)}).map(function(n){return[n.id,project(n)]}));const edges=graph.edges.filter(function(e){return projected.has(e.from)&&projected.has(e.to)}).map(function(e){return{e:e,a:projected.get(e.from),b:projected.get(e.to),z:(projected.get(e.from).z+projected.get(e.to).z)/2}}).sort(function(a,b){return b.z-a.z});edges.forEach(function(v){ctx.beginPath();ctx.moveTo(v.a.x,v.a.y);ctx.lineTo(v.b.x,v.b.y);ctx.strokeStyle=selected&&(v.e.from===selected.id||v.e.to===selected.id)?"#67e8f9aa":"#52627a32";ctx.lineWidth=selected&&(v.e.from===selected.id||v.e.to===selected.id)?1.5:.7;ctx.stroke()});const ordered=nodes.filter(function(n){return visible.has(n.id)}).map(function(n){return{n:n,p:projected.get(n.id)}}).sort(function(a,b){return b.p.z-a.p.z});ordered.forEach(function(v){const n=v.n,p=v.p,important=n.kind==="feature"||n.kind==="concern"||n.kind==="module",r=(important?5.5:3)+Math.min(5,Math.sqrt(n.degree))*p.d*.45;ctx.beginPath();ctx.arc(p.x,p.y,r*p.d,0,Math.PI*2);ctx.fillStyle=colors[n.kind]||"#94a3b8";ctx.globalAlpha=Math.max(.28,Math.min(1,p.d));ctx.fill();if(n===selected){ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke()}ctx.globalAlpha=1;if(n===selected||n===hover||important&&p.d>.85){ctx.font=(n===selected?"600 13px":"11px")+" system-ui";ctx.fillStyle="#e2e8f0";ctx.fillText(n.label,p.x+r*p.d+4,p.y+3)}})}draw();
function nearest(x,y){let best=null,dist=18;nodes.forEach(function(n){if(!visible.has(n.id))return;const p=project(n),d=Math.hypot(p.x-x,p.y-y);if(d<dist){dist=d;best=n}});return best}
function safeFileHref(path){const parts=String(path).replaceAll("\\\\","/").split("/");if(parts.some(function(part){return!part||part==="."||part===".."}))return null;return"../"+parts.map(function(part){return encodeURIComponent(part).replaceAll("'","%27")}).join("/")}
function show(n){selected=n;settle=Math.min(settle,650);updateVisible();if(!n){panel.innerHTML="<h2>Explore the graph</h2><div class=muted>Click a node to inspect evidence and connections.</div>";return}const links=(adj.get(n.id)||[]).slice(0,30).map(function(a){const other=byId.get(a.id);return"<span class=badge>"+(a.out?"→ ":"← ")+escapeHtml(a.edge.kind)+" · "+escapeHtml(other?other.label:a.id)+"</span>"}).join("");const citations=(n.citations||[]).map(function(c){return"<div>"+escapeHtml(c.path)+":"+c.line+"</div>"}).join("")||"<span class=muted>No direct citation</span>";const path=n.guide||n.path,href=path?safeFileHref(path):null;panel.innerHTML="<h2>"+escapeHtml(n.label)+"</h2><span class=badge>"+escapeHtml(n.kind)+"</span><span class=badge>"+escapeHtml(n.provenance)+"</span><div class=section>"+escapeHtml(n.summary||n.path||n.scope||n.id)+"</div>"+(href?"<div class=section links><b>Open</b><a href='"+href+"'>"+escapeHtml(path)+"</a></div>":"")+"<div class=section><b>Connections</b><div>"+(links||"<span class=muted>No visible connections</span>")+"</div></div><div class=section><b>Evidence</b>"+citations+"</div>"}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,function(c){return({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"})[c]})}
canvas.addEventListener("pointerdown",function(e){drag=true;lastX=e.clientX;lastY=e.clientY;canvas.classList.add("drag")});addEventListener("pointerup",function(){drag=false;canvas.classList.remove("drag")});addEventListener("pointermove",function(e){if(drag){yaw+=(e.clientX-lastX)*.006;pitch=Math.max(-1.45,Math.min(1.45,pitch+(e.clientY-lastY)*.006));lastX=e.clientX;lastY=e.clientY}else{hover=nearest(e.clientX,e.clientY)}});canvas.addEventListener("wheel",function(e){e.preventDefault();zoom=Math.max(.25,Math.min(4,zoom*Math.exp(-e.deltaY*.001)))},{passive:false});canvas.addEventListener("click",function(e){if(Math.abs(e.clientX-lastX)<5&&Math.abs(e.clientY-lastY)<5)show(nearest(e.clientX,e.clientY))});canvas.addEventListener("dblclick",function(e){const n=nearest(e.clientX,e.clientY);if(n){nodes.forEach(function(v){v.x-=n.x;v.y-=n.y;v.z-=n.z});settle=0;show(n)}});
[search,kind,depth].forEach(function(el){el.addEventListener("input",function(){settle=0;updateVisible()})});document.getElementById("reset").onclick=function(){yaw=.3;pitch=-.18;zoom=1;selected=null;search.value="";kind.value="all";depth.value="0";settle=0;updateVisible();show(null)};document.getElementById("spin").onclick=function(){spinning=!spinning;this.textContent=spinning?"Pause spin":"Resume spin"};
Array.from(new Set(nodes.map(function(n){return n.kind}))).sort().forEach(function(k){const o=document.createElement("option");o.value=k;o.textContent=k;kind.appendChild(o)});document.getElementById("legend").innerHTML=Object.keys(colors).map(function(k){return"<span><i class=dot style='background:"+colors[k]+"'></i>"+k+"</span>"}).join("");updateVisible();
</script></body></html>\n`;
}
