import { createHash, randomUUID } from "node:crypto";
import { cp, mkdtemp, readdir, rm, unlink } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, isAbsolute, join, relative } from "node:path";
import { z } from "zod";
import { atomicWrite, exists, harnessDir, posixPath, readJson, readText, writeJson } from "../../core/src/index.js";
import { extractPending, GENERATED_MARKER, PENDING_END, PENDING_START } from "./agents-md.js";
import { providers } from "./providers.js";

const SNAPSHOT_LIMIT = 20;
const ARCHIVE_DIRECTORY = "generations";
const generatedDirectories = [".harnessme/references/", ".harnessme/agent-pack/", ".harnessme/features/"];
const candidatePaths = [
  "AGENTS.md", ".ruler/AGENTS.md", "CLAUDE.md", ".github/workflows/harnessme.yml",
  ".harnessme/FEATURES.md", ".harnessme/knowledge-graph.json",
  ...providers.map((provider) => provider.nativeArtifact),
];

const ManagedPathSchema = z.string().min(1).refine((path) => {
  const normalized = posixPath(path);
  return !isAbsolute(path) && !/^[A-Za-z]:\//u.test(normalized) && !normalized.split("/").includes("..");
}, "Managed paths must stay inside the repository.");

const GenerationSnapshotSchema = z.object({
  schemaVersion: z.literal(1),
  id: z.string().min(1),
  createdAt: z.string().datetime(),
  reason: z.enum(["before-sync", "sync", "before-rollback", "rollback"]),
  trackedPaths: z.array(ManagedPathSchema),
  files: z.array(z.object({ path: ManagedPathSchema, content: z.string() })),
});

export type GenerationSnapshot = z.infer<typeof GenerationSnapshotSchema>;
export type GenerationReason = GenerationSnapshot["reason"];

export interface GenerationSummary {
  id: string;
  createdAt: string;
  reason: GenerationReason;
  files: number;
}

export interface GenerationChange {
  path: string;
  status: "added" | "modified" | "deleted";
  additions: number;
  deletions: number;
}

function archiveDir(root: string): string {
  return join(harnessDir(root), ARCHIVE_DIRECTORY);
}

function safeRelative(root: string, path: string): string {
  return posixPath(relative(root, path));
}

async function discoverManagedPaths(root: string, directory = root): Promise<string[]> {
  if (!await exists(directory)) return [];
  const result: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) continue;
    const relativePath = safeRelative(root, join(directory, entry.name));
    if (entry.isDirectory()) {
      if ([".git", "node_modules", "dist", "coverage", ".harnessme/generations"].includes(relativePath)) continue;
      result.push(...await discoverManagedPaths(root, join(directory, entry.name)));
      continue;
    }
    if (generatedDirectories.some((prefix) => relativePath.startsWith(prefix)) || [".harnessme/FEATURES.md", ".harnessme/knowledge-graph.json"].includes(relativePath)) {
      result.push(relativePath);
      continue;
    }
    if (!candidatePaths.includes(relativePath) && entry.name !== "AGENTS.md") continue;
    const content = await readText(join(directory, entry.name));
    if (content.startsWith(GENERATED_MARKER) || /generated by (?:HarnessME|Ruler)/iu.test(content)) result.push(relativePath);
  }
  return result;
}

async function readFiles(root: string, paths: string[]): Promise<Array<{ path: string; content: string }>> {
  const files: Array<{ path: string; content: string }> = [];
  for (const path of [...new Set(paths)].sort()) {
    const absolute = join(root, path);
    if (await exists(absolute)) files.push({ path, content: await readText(absolute) });
  }
  return files;
}

function fingerprint(snapshot: Pick<GenerationSnapshot, "trackedPaths" | "files">): string {
  return createHash("sha256").update(JSON.stringify({ trackedPaths: snapshot.trackedPaths, files: snapshot.files }), "utf8").digest("hex");
}

async function loadSnapshot(root: string, id: string): Promise<GenerationSnapshot> {
  if (!/^[A-Za-z0-9._-]+$/u.test(id)) throw new Error("Invalid generation identifier.");
  const path = join(archiveDir(root), `${id}.json`);
  if (!await exists(path)) throw new Error(`Unknown harness generation: ${id}`);
  return readJson(path, GenerationSnapshotSchema);
}

export async function listGenerations(root: string): Promise<GenerationSummary[]> {
  const directory = archiveDir(root);
  if (!await exists(directory)) return [];
  const snapshots: GenerationSnapshot[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".json")) continue;
    snapshots.push(await readJson(join(directory, entry.name), GenerationSnapshotSchema));
  }
  return snapshots
    .sort((left, right) => right.createdAt.localeCompare(left.createdAt) || right.id.localeCompare(left.id))
    .map((snapshot) => ({ id: snapshot.id, createdAt: snapshot.createdAt, reason: snapshot.reason, files: snapshot.files.length }));
}

export async function captureGeneration(root: string, reason: GenerationReason, paths: string[] = []): Promise<GenerationSummary> {
  const discovered = await discoverManagedPaths(root);
  const requested = await readFiles(root, paths);
  const requestedManaged = requested.filter((file) =>
    generatedDirectories.some((prefix) => file.path.startsWith(prefix))
    || [".harnessme/FEATURES.md", ".harnessme/knowledge-graph.json"].includes(file.path)
    || file.content.startsWith(GENERATED_MARKER)
    || /generated by (?:HarnessME|Ruler)/iu.test(file.content),
  );
  const trackedPaths = [...new Set([...discovered, ...requestedManaged.map((file) => file.path)])].sort();
  const files = await readFiles(root, trackedPaths);
  const existing = await listGenerations(root);
  if (existing[0]) {
    const latest = await loadSnapshot(root, existing[0].id);
    if (fingerprint(latest) === fingerprint({ trackedPaths, files })) return existing[0];
  }
  const createdAt = new Date().toISOString();
  const id = `${createdAt.replaceAll(":", "-")}-${randomUUID().slice(0, 8)}`;
  const snapshot: GenerationSnapshot = { schemaVersion: 1, id, createdAt, reason, trackedPaths, files };
  await atomicWrite(join(archiveDir(root), ".gitignore"), "*\n!.gitignore\n");
  await writeJson(join(archiveDir(root), `${id}.json`), snapshot);
  const snapshots = await listGenerations(root);
  for (const stale of snapshots.slice(SNAPSHOT_LIMIT)) await unlink(join(archiveDir(root), `${stale.id}.json`));
  return { id, createdAt, reason, files: files.length };
}

function lineCounts(before: string, after: string): { additions: number; deletions: number } {
  const left = before.split(/\r?\n/u);
  const right = after.split(/\r?\n/u);
  let prefix = 0;
  while (prefix < left.length && prefix < right.length && left[prefix] === right[prefix]) prefix += 1;
  let suffix = 0;
  while (suffix < left.length - prefix && suffix < right.length - prefix && left[left.length - 1 - suffix] === right[right.length - 1 - suffix]) suffix += 1;
  return { additions: right.length - prefix - suffix, deletions: left.length - prefix - suffix };
}

async function compareRoots(beforeRoot: string, afterRoot: string, paths: string[]): Promise<GenerationChange[]> {
  const changes: GenerationChange[] = [];
  for (const path of [...new Set(paths)].sort()) {
    const beforePath = join(beforeRoot, path);
    const afterPath = join(afterRoot, path);
    const before = await exists(beforePath) ? await readText(beforePath) : undefined;
    const after = await exists(afterPath) ? await readText(afterPath) : undefined;
    if (before === after) continue;
    const counts = lineCounts(before ?? "", after ?? "");
    changes.push({ path, status: before === undefined ? "added" : after === undefined ? "deleted" : "modified", ...counts });
  }
  return changes;
}

async function resolveTarget(root: string, id?: string): Promise<GenerationSnapshot> {
  if (id) return loadSnapshot(root, id);
  const generations = await listGenerations(root);
  const target = generations[1] ?? generations[0];
  if (!target) throw new Error("No archived harness generation is available.");
  return loadSnapshot(root, target.id);
}

async function restoreContent(root: string, path: string, archived: string): Promise<string> {
  if (path !== "AGENTS.md" || !archived.includes(PENDING_START) || !archived.includes(PENDING_END)) return archived;
  const currentPath = join(root, path);
  const current = await exists(currentPath) ? await readText(currentPath) : "";
  const pending = extractPending(current);
  const start = archived.indexOf(PENDING_START) + PENDING_START.length;
  const end = archived.indexOf(PENDING_END);
  const body = `\n### Pending updates (edit directly — no command needed)\nShipped or materially changed a feature? Add one dated bullet below.\n\n${pending ? `${pending}\n` : ""}`;
  return `${archived.slice(0, start)}${body}${archived.slice(end)}`;
}

export async function previewGenerationRollback(root: string, id?: string): Promise<{ generation: GenerationSummary; changes: GenerationChange[] }> {
  const target = await resolveTarget(root, id);
  const temporary = await mkdtemp(join(tmpdir(), "harnessme-rollback-preview-"));
  try {
    for (const file of target.files) await atomicWrite(join(temporary, file.path), await restoreContent(root, file.path, file.content));
    const currentPaths = await discoverManagedPaths(root);
    const changes = await compareRoots(root, temporary, [...target.trackedPaths, ...currentPaths]);
    return { generation: { id: target.id, createdAt: target.createdAt, reason: target.reason, files: target.files.length }, changes };
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
}

export async function rollbackGeneration(root: string, id?: string): Promise<{ generation: GenerationSummary; changes: GenerationChange[] }> {
  const preview = await previewGenerationRollback(root, id);
  const target = await loadSnapshot(root, preview.generation.id);
  await captureGeneration(root, "before-rollback");
  const targetFiles = new Map(target.files.map((file) => [file.path, file.content]));
  const currentPaths = await discoverManagedPaths(root);
  for (const path of [...new Set([...target.trackedPaths, ...currentPaths])]) {
    let content = targetFiles.get(path);
    const absolute = join(root, path);
    if (content !== undefined) content = await restoreContent(root, path, content);
    if (content !== undefined) await atomicWrite(absolute, content);
    else if (await exists(absolute)) await rm(absolute, { force: true });
  }
  await captureGeneration(root, "rollback", target.trackedPaths);
  return preview;
}

export async function previewHarnessSync(root: string, targetIds?: string[]): Promise<GenerationChange[]> {
  const temporary = await mkdtemp(join(tmpdir(), "harnessme-sync-preview-"));
  const copyRoot = join(temporary, basename(root) || "repository");
  try {
    await cp(root, copyRoot, {
      recursive: true,
      filter: (source) => {
        const path = safeRelative(root, source);
        return ![".git", "node_modules", "dist", "coverage", ".harnessme/generations"].some((excluded) => path === excluded || path.startsWith(`${excluded}/`));
      },
    });
    const { syncHarness } = await import("./sync.js");
    const result = await syncHarness(copyRoot, targetIds, { archive: false });
    return await compareRoots(root, copyRoot, [...result.files, ...await discoverManagedPaths(root), ...await discoverManagedPaths(copyRoot)]);
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
}
