export const nonCodingClientInstructions = [
  "Before any repository file edit or Git/PR-related action, call `harnessme_preflight` with every intended or affected repository-relative path.",
  "Read and follow every instruction document returned by the preflight result.",
  "If the result status is `approval-required`, stop and request explicit human approval before modifying files or continuing the Git/PR action. Never infer approval or approve your own change.",
  "After approval, draft the required critical-change record; a listed human approver must still approve the exact staged content.",
  "If `harnessme_preflight` is unavailable, use the filesystem tool to read `AGENTS.md`, `.harnessme/CRITICAL.md`, and the nearest module-level `AGENTS.md` before acting, then apply the same stop-and-ask rule.",
].join(" ");

export function renderClaudeDesktopInstructions(): string {
  return `<!-- Generated by HarnessME. Do not edit directly. -->
# Claude Desktop integration

Claude Desktop does not automatically load repository-local \`AGENTS.md\` files or Claude Code hooks. Add the HarnessME MCP server alongside your filesystem/git server, then paste the text below into the Claude Desktop Project's custom instructions.

## MCP configuration

Replace the placeholder with this repository's absolute path:

\`\`\`json
{
  "mcpServers": {
    "harnessme": {
      "command": "harnessme",
      "args": ["mcp", "--root", "<absolute-repository-path>"]
    }
  }
}
\`\`\`

## Claude Desktop Project custom instructions

\`\`\`text
${nonCodingClientInstructions}
\`\`\`

The MCP instructions and preflight result are advisory because a separate filesystem/git MCP server owns its write operations. HarnessME's pre-commit gate and CI gate remain the hard enforcement layer.
`;
}
